"""
Django settings for exchanger project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','%l@&95($!@-_)=ucorv!-x$&f0!381oiae_+cavn+kux9752^9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['instexchanger.herokuapp.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exchanger_app',
    'blog',
    'custom_admin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exchanger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exchanger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
"""
{
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':'exchangerdb',
        'USER':'exchanger',
        'PASSWORD':'exchangerpass',
        'HOST':'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#api end point
api_link = '/start'
api_key = '3222bb3892a7984bd43d91f6db1853c4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "assets"),
    os.path.join(BASE_DIR, 'media')

]


db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# the node details
bitcoin_user = 'exchanger'
bitcoin_password = 'exchangerpass'

bitcoin_cash_user = 'exchanger12'
bitcoin_cash_password = 'exchangerpass12'

litecoin_user = 'exchanger'
litecoin_password = 'exchangerpass'

address_user = 'tester'

master_eth_add = '0x50838ccC4D81eF79Bd9cdee79976C11190833e3b'
master_eth_private = ''

min_confirmation = 1

main_test_label = 'testm'

b_a_k ='beQWNG1BHQupGnCANx51Jw96VsxT1pAhyzNIpcShJpfPsYyVOmgUpb5memo2XZ74'
b_a_p = 'NrH2t7PRJERLfPz2XdwdbLYHtttYJWk7u7yJQGwmx06jBJiG9Wb4itVK1uPNOdyo'


ltc_provider_acc = 'testbalance'

monero_user = 'exchanger'
monero_password = 'exchangerpass'

eth_test_provider_p = '0xc57beb2188e830a11cf710f5f3a11177761d41e7fe0ce5425a6c46a3054f8d29'
eth_test_provider_ad = '0x5c4542d89ca5766EBd9AbCE36049FD8AA79d484F'


mon_receiver_index  = 1
MEDIA_URL = '/assets/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'assets/media')
