# Generated by Django 2.2.3 on 2019-08-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='assets/media/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
