# Generated by Django 2.2.3 on 2019-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190817_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
