# Generated by Django 2.2.3 on 2019-09-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_clicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_desc', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='meta_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='meta_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
