# Generated by Django 2.2.3 on 2019-08-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('test_address', models.CharField(max_length=1000)),
                ('balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=1000)),
                ('return_address', models.CharField(max_length=1000)),
                ('refund_address', models.CharField(max_length=1000)),
                ('recv_address', models.CharField(max_length=1000)),
                ('in_currency', models.CharField(max_length=10)),
                ('out_currency', models.CharField(max_length=10)),
                ('amount_in', models.BigIntegerField(default=0)),
                ('fees', models.IntegerField(default=5)),
                ('amount_out', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
