# Generated by Django 2.2.3 on 2019-08-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash_tr',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
