# Generated by Django 2.2.3 on 2019-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0003_listener_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eth_wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=350)),
                ('private_key', models.CharField(max_length=350)),
                ('user_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_out',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fees',
            field=models.IntegerField(default=2),
        ),
    ]
