# Generated by Django 2.2.3 on 2019-09-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0005_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
