# Generated by Django 2.2.3 on 2019-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0006_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='hacking_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
