# Generated by Django 2.2.3 on 2019-09-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_currencies_s_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
